/* Update short name files */
PRAGMA encoding = "UTF-8";
UPDATE PLAYERFILE SET SHORTFILENAME = replace(FILENAME, (select lower(FILEDIR) from CONFIG), '');
UPDATE PLAYERFILE SET ISUSED = 1;
UPDATE PLAYERFILE SET ISUSED = 0 WHERE NOT EXISTS(select 1 from PLAYERMAP where lower(SHORTFILENAME)=lower(FACEFILE) or lower(SHORTFILENAME)=lower(HAIRFILE));
UPDATE PLAYERMAP SET EXISTSFACE = 1, EXISTSHAIR = 1;
UPDATE PLAYERMAP SET EXISTSFACE = 0 where not exists(select 1 from PLAYERFILE where lower(SHORTFILENAME)=lower(FACEFILE));
UPDATE PLAYERMAP SET EXISTSHAIR = 0 where not exists(select 1 from PLAYERFILE where lower(SHORTFILENAME)=lower(HAIRFILE));
ALTER TABLE PLAYERCSV ADD COLUMN ISCONFIG INTEGER default 1;
UPDATE PLAYERCSV SET ISCONFIG = 0 where not exists(select 1 from PLAYERMAP where PLAYERMAP.ID=PLAYERCSV.ID);

INSERT INTO TEAM select distinct (CLUBTEAM) from PLAYERCSV where CLUBTEAM <> '' order by CLUBTEAM;
INSERT INTO COUNTRY select distinct NATIONALITY from PLAYERCSV where NATIONALITY <> '' order by NATIONALITY;